language: node_js
script: karma start karma.conf.js --single-run
node_js:
- "node"

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- npm install -g karma-cli
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

addons:
  chrome: stable
